---
title: "report"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{report}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = FALSE
)
```

```{r setup}
library(tbr)
table_data              <- table("of dataset")
table_one               <- table("one")

figure_map              <- figure("of map")
figure_age              <- figure("of age")
figure_maturation       <- figure("of maturation")
figure_catch            <- figure("of catch")
figure_catch_at_age     <- figure("of catch at age")
figure_f                <- figure("of F")
figure_f_trend          <- figure("of F trend")
figure_index            <- figure("of index")

figure_b_ssb            <- figure("of B and SSB")
figure_n_at_age         <- figure("of N at age trend")
figure_b_at_age         <- figure("of B at age trend")
figure_r_rps            <- figure("of R and RPS trend")
figure_m_effect         <- figure("of M effect on B and SSB estimation")
figure_f_at_age         <- figure("of F at age trend")
figure_harvest_rate     <- figure("of harvest rate")
figure_harvest_rate     <- figure("of harvest rate")
table_assessment_result <- table("of assessment result")

table_two               <- table("spr(f2019), %spr(F20XX-2019)")
table_f_and_pspr        <- table("of %SPR trend on F by year")
table_ypr_spr           <- table("of relationship between YPR and %SPR")

table_sr_param <- table("of SR relationship parameters")
table_ssb_r <- table("of SSB-R relationship")

table_three <- table("three")
table_six <- table("six")

table_four <- table("SSB2019/SBtarget, F2019/Fmsy")
table_stock_level <- table("of stock level")
figure_ssb_f <- figure("- kobe plot")
```
# データセット

```{r}
table_data()
```

# 生態

## 分布・回遊

```{r}
figure_map()
```

## 年齢・成長

```{r}
figure_age()
```


## 成熟・産卵

```{r}
figure_maturation()
```


## 非捕食関係

# 漁業の状況

## 漁業の概要

## 漁獲量の推移

```{r}
figure_catch()
figure_catch_at_age()
```

## 漁獲努力量

```{r}
figure_f_trend()
figure_f()
```


# 資源の状態

## 資源評価の方法

## 資源量指標値の推移

```{r}
figure_index()
```

## 資源量と漁獲圧の推移

```{r}
table_one()
```


```{r}
figure_b_ssb()
figure_n_at_age()
figure_b_at_age()
figure_r_rps()
figure_m_effect()
figure_f_at_age()
figure_harvest_rate()
figure_harvest_rate()
table_assessment_result()
```

## 加入量あたり漁獲量


```{r}
table_two()
table_f_and_pspr()
table_ypr_spr()
```

## 再生産関係


```{r}
table_sr_param()
table_ssb_r()
```


## 現在の環境下においてMSYを実現する水準および管理基準値

```{r}
table_three()
table_six()
```

## 資源の水準・動向および漁獲圧の水準

```{r}
table_four()
table_stock_level()
figure_ssb_f()
```
